package main

import (
	"flag"
	"fmt"
	"github.com/davecgh/go-spew/spew"
	"github.com/jacob-elektronik/gofact/messages/handler"
	"github.com/jacob-elektronik/gofact/parser"
	"os"
	"text/tabwriter"
	//"github.com/davecgh/go-spew/spew"
)

var message = flag.String("message", "", "edifact message.edi file path")
var subset = flag.String("subset", "edifact", "supportet subset : eancom")
var printTokens = flag.Bool("ptokens", false, "print tokens generated by the lexer")
var printSegments = flag.Bool("psegments", false, "print segments generated by the parser")

func main() {

	flag.Parse()
	if *message != "" {
		p := parser.NewParser(*message, *subset)
		err := p.ParseEdiFactMessageConcurrent()
		fmt.Println(err)

		if *printTokens {
			for t :=range p.Tokens {
				const padding = 3
				w := tabwriter.NewWriter(os.Stdout, 0, 0, padding, ' ', tabwriter.TabIndent|tabwriter.Debug)
				_, err := fmt.Fprintln(w, t)
				if err != nil {
					fmt.Println(err)
				}
				err = w.Flush()
				if err != nil {
					fmt.Println(err)
				}
			}
		}

		if *printSegments {
			const padding = 3
			w := tabwriter.NewWriter(os.Stdout, 0, 0, padding, ' ', tabwriter.TabIndent|tabwriter.Debug)
			for _, s := range p.Segments {
				_, err := fmt.Fprintln(w, s)
				if err != nil {
					fmt.Println(err)
				}
			}
			err := w.Flush()
			if err != nil {
				fmt.Println(err)
			}
		}
		order, _ := handler.UnmarshalOrder(p.Segments, p.CtrlBytes)
		//fmt.Println(order)
		spew.Dump(order)
	} else {
		fmt.Println("no edi message to parse")
	}

}
